name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm ci
      - name: Run ESLint
        run: npx eslint src/**/*.{js,jsx,ts}
      - name: Run Typescript
        run: tsc -p tsconfig.json --noEmit
